image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Install Solana
      sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.15/install)"
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      
      # Install Anchor
      cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --tag v0.29.0
      
      # Persist PATH
      echo 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
      echo 'source "$HOME/.cargo/env"' >> ~/.bashrc
