image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      
      # Install Anchor 0.29.0 without AVM
      cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --tag v0.29.0 --force
      
      # Install Solana
      sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.15/install)"
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      
      # Persist PATH
      echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
      echo 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
